### PR TITLE
Added -ntlm option to enable NTLM auth.

### PR DESCRIPTION
**Pull request by ghost**
This merge Request adds ntlmssp support to the winrm cli tool.

Regards,
Tim.

### CODE REVIEW

**Comment by ghost** [comment]
@masterzen would this be something you would consider merging ?

**Comment by masterzen** [comment]
@tim-dawson-nv,

I'm very sorry for my lack of answer to this ticket. 

I have absolutely no objection regarding the functionality or your code, and many thanks for contributing a new feature. But since you removed the vendor directory and changed the `Godeps`, I think that it would be awesome to:
* move that project to [go modules](https://github.com/golang/go/wiki/Modules)
* change travis.yml to test on Go 1.11+ instead of ancient go versions that nobody uses anymore

Do you think that's something you could handle in this PR?
Feel free to say no, I'll then merge this PR as is :)

Thanks!

**Comment by ghost** [comment]
Sure thing I can bring the go versions up to date. And look at go modules

**Comment by tristanmorgan** [comment]
HI @tim-dawson-nv,

In another PR I have updated the build to use go modules and upped the golang version. if you would like to update your PR, the ground work has been done for you.

Regards,

Tristan

**Comment by ghost** [comment]
I totally forgot about this, I'll have a look tomorrow. Cheers.On 6/02/2020 13:39, Tristan <notifications@github.com> wrote:HI @tim-dawson-nv,
In another PR I have updated the build to use go modules and upped the golang version. if you would like to update your PR, the ground work has been done for you.
Regards,
Tristan

**Comment by ghost** [comment]
That should do the job

**Review by masterzen — APPROVED** [review]
Looks correct to me.
Thanks for your contribution !

**Pull request merged**
